global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'product_service'
    static_configs:
      - targets: ['host.docker.internal:8082'] # Assuming product_service metrics are on port 8082
      #  - targets: ['product_service:8082'] # Assuming product_service metrics are on port 8082
  - job_name: 'user_service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  # - job_name: 'user_service' # Example: Add your services here
  #   static_configs:
  #     - targets: ['user_service:9100'] # Assuming metrics are exposed on port 9100

  # - job_name: 'cart_bff' # Example: Add your bffs here
  #   static_configs:
  #     - targets: ['cart_bff:9101']
# Add more scrape configurations for each of your microservices and BFFs
# once they expose a /metrics endpoint compatible with Prometheus.
####
# apiVersion: 1

# datasources:
#   - name: Prometheus
#     type: prometheus
#     access: proxy
#     url: http://digital_mono_prometheus:9090 # Updated to use container name
#     isDefault: true
#     editable: true
#     jsonData:
#       timeInterval: "15s"
#       exemplarTraceIdDestinations: [] # Add if using exemplars with tracing
# ####
# apiVersion: 1

# providers:
#   - name: 'Default Dashboards' # A more descriptive name
#     orgId: 1
#     folder: '' # Dashboards will appear in the General folder
#     type: file
#     disableDeletion: false
#     editable: true
#     options:
#       path: /etc/grafana/provisioning/dashboards/default # Path inside the container
#       # You will need to place your dashboard JSON files in
#       # digital-mono/deployments/docker-compose/grafana/provisioning/dashboards/default/
