apiVersion: v1
kind: Service
metadata:
  name: cart-bff
  namespace: digital-mono
spec:
  selector:
    app: cart-bff
  ports:
    - protocol: TCP
      port: 9080 # Port other services will use to reach cart-bff
      targetPort: 9080 # Container port
