apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: digital-mono
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.digital-mono.svc.cluster.local:9090
        isDefault: true
        editable: true
