apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: digital-mono
type: Opaque
data:
  POSTGRES_USER: b21uaV91c2Vy # echo -n "omni_user" | base64
  POSTGRES_PASSWORD: c3Ryb25nX3Bhc3N3b3Jk # echo -n "strong_password" | base64
